### ISSUE TITLE
[feature] add lazy load init tooltip.

### ISSUE THREAD

**Issue by dimensi** [hekigan/vue-directive-tooltip#21]
### Feature
Hi, can you add lazy initialization tooltip? If I add tooltip on buttons in rows of table. On 20 rows, i get 20 initializations. It's too many. And can you add auto-destroy please like here https://github.com/Akryum/v-tooltip/blob/master/src/v-tooltip.js#L239. Thx in advance.
I lost half fps, because tooltip.js autoupdate positions on scroll.

![vokoscreen-2017-10-22_18-28-56](https://user-images.githubusercontent.com/11390039/31863508-e954043a-b756-11e7-8738-74c580cd2f2a.gif)

**Comment by hekigan** [comment]
That's a very interesting performance issue.
I did a test with a 1000 rows to see how it goes.
If you just scroll normally, there no performance issue. 
BUT if you go straight to top/bottom or use the spacebar, indeed, there is a huge drop in frame rate.

I do not like that and I am going to work on it.

**Comment by victornpb** [comment]
I up that, also why do you have to create an id for every tooltip?

**Comment by jardicc** [comment]
It makes my UI unusable. It updates css positions on scroll to fast. If I won't be able to find fix then I will replace these tooltips with a different library.

**Comment by hekigan** [comment]
@victornpb the need for the id for tooltip is for the *html* bit.
Since it can be an independent node, it's the the simplest in terms of performance because it avoid doing a lookup to find it.

@jardicc You are making a good point.
I believe it will be addressed once I finish the original demand. It won't be *lazy loading* per say, but create/destroy on usage. It should be way better in terms of performance.
I should be done within a week.

**Comment by victornpb** [comment]
Afaik querying the DOM is more expensive than a object lookup. Anyway you just have to instantiate visible tooltips, then remove them from DOM and any references to it as soon as possible. This will clear the DOM, references and you don’t have to calculate any positioning.

You can have hundreds of tooltips on a page, but you usually will have only a few being active, so it doesn’t make sense to have all of them active all the time.

**Comment by jardicc** [comment]
@victornpb Position calculating is still needed because you can hover element and scroll mouse at the same time. So tooltip can be outside of the hovered element if you don't calculate position.

**Comment by victornpb** [comment]
@jardicc yes but you don't need to update invisible tooltips on scroll. I would not even mount them on the DOM since the more elements you have the slower css computations are in general.

When a tooltip is fired, append it to dom and update only mounted elements, when a tooltip is hidden, remove it from the three, and you don't have to calculate or update its position.

**Comment by hekigan** [comment]
@jardicc 
It's been quite a while, but I pushed a new version -v1.5.1- which addresses the performance issue.
I can have now more than a thousand tooltips set and there is no drop in performance.

I will not close yet this thread because I did not do the lazy loading part yet.
