### ISSUE TITLE
[feature] updated content binding value is ignored

### ISSUE THREAD

**Issue by alex3683** [hekigan/vue-directive-tooltip#23]
### Feature

Actually, I don't know if this is a bug or a feature request. I must admit that I simply expected this to be working. :-) Now the actual issue:
When binding the tooltip to a value, the tooltip renders with the first value it reads from the binding. Whenever the binding's value changes henceforth, that change is not reflect. The tooltip still shows the initial value of the binding. I made an example here: https://codepen.io/anon/pen/EbGbgL
Simply edit the value in the input and you'll see, that the tooltip won't show that new text.

**Comment by hekigan** [comment]
The code to make it work from your example is the following:

`<span v-tooltip="{content: tooltipText}" class="tooltip-origin">tooltip</span>`

But I understand why it could be confusing that the simple way does not work the same way.
I will update that to be able to either soon.

This comment was helpful, since I did not notice that issue, thank you.

**Comment by traykovn** [comment]
I tried exactly that:

`<span v-tooltip="{content: tooltipText}" class="tooltip-origin">tooltip</span>`

And it didn't work. This was the first thing I thought of, since it is intuitive, but didn't manage to change the value.

**Comment by traykovn** [comment]
Actually this works:

`<span v-tooltip="{content: tooltipText}" class="tooltip-origin">tooltip</span>`

It wasn't working because of my mistake.

**Comment by hekigan** [comment]
Done!
