### ISSUE TITLE
Include 'Vue.use(Tooltip);' step to instructions.

### ISSUE THREAD

**Issue by weislanes** [hekigan/vue-directive-tooltip#3]
There's no instructions stating a user must register the directive using:

```
import Tooltip from 'vue-directive-tooltip';
Vue.use(Tooltip);
```

Please include this. (And thanks for making this!).

**Comment by hekigan** [comment]
Hello!

You are completely right.
I did not put it in as for the ES5 version, it is automatically done
https://github.com/hekigan/vue-directive-tooltip/blob/master/src/index.js#L6

But for ES6, it is another matter. And so, yes I will add it now  :)

**Comment by hekigan** [comment]
Done:
https://github.com/hekigan/vue-directive-tooltip/commit/7144373148556b9c9e3ff87150a57cdcf80ced5c

**Comment by weislanes** [comment]
Nice one.!

I see that it only borrows some of the options from Popper.js. Is there a plan to extend it to include stuff like closing only click away etc? Or is that outside the scope of what this should do?

Basically I'm looking to create a popup menu similar to this: https://cdn.dribbble.com/users/79601/screenshots/2254492/configurator-popup.png and wondering if I should lean on this library or create one from scratch.

**Comment by hekigan** [comment]
There is a plan to expand the options.
To be honest, I did this implementation because I needed it for a personal project and did not have time to implement more than the basic stuff.

It should not be difficult to add to it, but I want to be sure that the usage will be simple and in line with most Vue directives mechanics.

Now, after looking at your screenshot, what you need would some kind of `target` property to fill the content of the tooltip. Am I right? Or did you think of a different kind of implementation?
