### ISSUE TITLE
Extend Directive

### ISSUE THREAD

**Issue by daverogers** [hekigan/vue-directive-tooltip#32]
```js
import Tooltip from 'vue-directive-tooltip'

Vue.use(Tooltip, {
    delay: 200,
    placement: 'top',
    class: 'our-tooltip',
    triggers: ['hover'],
    offset: 0
});
```

So this works great, but I'd like to extend the package to always use those defaults in every instance - our company has a lot of separate apps so we don't use the same instance of Vue. I've extended filters and components before, but I'm not finding anything on extending directives. Is it possible? Or do we just need to have `Vue.use()` on every app?

**Comment by hekigan** [comment]
Hi, I know it's been a while since you asked and I am back from the dead.
To answer you, the directive is nothing else than a javascript Object.
So I don't see why you could not extend it. You could totally use the `config` property to implements your defaults. I never did it, but it should be doable.
